name: 'ZJU-nCov-Hitcarder Action'


on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
    
    
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            strname: ZJU_STRNAME
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            strname: ZJU_STRNAME2
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
            strname: ZJU_STRNAME3
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME4
            password: ZJU_PASSWORD4
            strname: ZJU_STRNAME4
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME5
            password: ZJU_PASSWORD5
            strname: ZJU_STRNAME5
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME6
            password: ZJU_PASSWORD6
            strname: ZJU_STRNAME6
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: XUMIAOSHANXUEHAO
            password: XUMIAOSHANPASSWORD
            strname: ZJU_STRNAME7
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Working
        uses: fatcatmat1994/ZJU_nCov@master
        with:
          strname: ${{ secrets[matrix.strname] }}
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
   
     
